"""update_missing_fields_for_artist

Revision ID: 744249dc7928
Revises: f50bf9310118
Create Date: 2022-07-25 12:11:26.888237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744249dc7928'
down_revision = 'f50bf9310118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'seeking_description')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'website_link')
    # ### end Alembic commands ###
